# Generated by VisualGDB

LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE    := ulltra-android-console2
#VisualGDBAndroid: AutoUpdateSourcesInNextLine
LOCAL_SRC_FILES := ../../AudioDriverStream.cpp ../../Controller.cpp ../../Discovery.cpp ../../JsonHttpClient.cpp ../../JsonHttpServer.cpp ../../JsonNode.cpp ../../LinkEval.cpp ../../LLCustomBlock.cpp ../../LLLink.cpp ../../LLTcp.cpp ../../LLUdpLink.cpp ../../LLUdpQWave.cpp ../../mongoose/mongoose.c ../../rtt/rtt.cpp ../../SimpleUdpReceiver.cpp ../../stress/stress.cpp ../../ulltra.cpp ../../UlltraProto.cpp ../../WindowsMM.cpp ulltra-android-console.c
LOCAL_C_INCLUDES := ../rtt
LOCAL_STATIC_LIBRARIES := 
LOCAL_SHARED_LIBRARIES := 
LOCAL_LDLIBS :=
LOCAL_LDFLAGS := -L$(SYSROOT)/usr/lib -llog
LOCAL_CPP_FEATURES := cxx_range_for exceptions rtti
LOCAL_CFLAGS    := 
LOCAL_CPPFLAGS    := -std=c++11
COMMON_SRC_FILES := $(LOCAL_SRC_FILES)
include $(BUILD_EXECUTABLE)