# Generated by VisualGDB
#APP_ABI := all
APP_ABI := all
#arm64-v8a
#APP_STL                 := stlport_static
APP_STL := gnustl_static
APP_CPPFLAGS := -std=c++11
APP_LDFLAGS :=-L$(SYSROOT)/usr/lib -llog
