# Generated by VisualGDB
APP_ABI := all
#APP_ABI := armeabi-v7a
#APP_ABI := arm64-v8a

#arm64-v8a
#APP_STL                 := stlport_static
APP_STL := gnustl_static
APP_CPPFLAGS := -std=c++11
APP_LDFLAGS :=-L$(SYSROOT)/usr/lib -llog
